### ISSUE TITLE
Remove hard coded references to /Users/tylercloutier/

### ISSUE THREAD

**Issue by king7532** [skylab-inc/Edge#4]
The package tests cannot be run because the build fails. There are [numerous](https://github.com/SwiftOnEdge/Edge/search?utf8=✓&q=tylercloutier) hard coded references to `/Users/tylercloutier/` in the project, which should be replaced with relative references to the package root.

**Comment by king7532** [comment]
Users should generate their own Xcode project using `swift package generate-xcodeproj`

**Comment by cloutiertyler** [comment]
Right, so this is an interesting problem. I was trying to configure an Xcode project to be compatible with Carthage, but there doesn't seem to be a way to avoid the references to absolute paths for the C project dependencies using `generate-xcodeproj`. I'm just going to pull the entire xcodeproj out and add it back to .gitignore.

**Comment by cloutiertyler** [comment]
Done. Thanks!

**Comment by king7532** [comment]
Should probably add something to the README file to inform new users of the framework how to generate the Xcode project.
